### ISSUE TITLE
Trouble running a custom Kraken2 DB

### ISSUE THREAD

**Issue by nataliering** [epi2me-labs/wf-metagenomics#72] opened 2023-11-02 13:30 UTC
### Ask away!

Hello,

I'm testing wf-metagenomics with some reads I generated with badread (10x coverage of a S. aureus strain with some AMR genes). When I run the demo data, or my badreads with the 16S/18S or Plus-PF8 databases, it all works beautifully.

But I've made a very small pathogen genome Kraken2 database (I think it's about 0.5 Gb total), along with the Bracken files, and the taxonomy I used to build the database and I just can't get it to run properly. I'm using EPI2ME 5.1.3 on Windows 10, downloaded and set up yesterday. I've run Kraken2 on our HPC with this database and it worked, so I don't think anything went badly wrong during the build...

Here's the log file for one of the failed runs:

[nextflow.stdout.txt](https://github.com/epi2me-labs/wf-metagenomics/files/13239314/nextflow.stdout.txt)

I'm sure I'm doing something stupid here, but can you help me figure out what it is please?

Thanks in advance, 
Nat

**Comment by SamStudio8** [comment] 2023-11-02 18:25
@nataliering Sorry to hear you have had trouble. We shall look in to this.

**Comment by SamStudio8** [comment] 2023-11-02 18:29
@nataliering Just to check, do you get the same error if you run the workflow again?

**Comment by nataliering** [comment] 2023-11-02 18:49
Hi Sam

Thanks! Yes, it happens every time I try with custom db. I tried it again with the 16S/18S db after the error started, and that still works fine.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nggvs** [comment] 2023-11-06 09:16
Hi @nataliering !
Thank you for using the workflow! I'm looking into the database problem. Just to be sure, when you are as you are using EPI2ME, to set up the run you are providing kraken2 as a folder  (in Reference Options), and the bracken file (Bracken kmer distance file). As well as the taxonomy database (in Reference Options). Could you indicate me how you have generated your database?

As this is going to change in the next release, you might one to try this new one to see if the problem persists (to do that in EPI2ME you would need to 1) open the w-metagenomics, 2) Switch revision 3) Choose prerelease) and then use your files as an input. In this case, the bracken file must be within the kraken2 database folder.
Thank you very much,

**Comment by nataliering** [comment] 2023-11-08 14:54
Hi Natalia

I tried switching to the prelease version, and it works! No idea what was going wrong with the released version, but I'll just stick with the prelease. :)

Thanks a lot for your help!

**Comment by nggvs** [comment] 2023-11-08 15:13
Hi @nataliering ,
Glad to hear that. 
Just to let you know, prerelease branch is not stable and may change. I will let you know once the stable one is released so that you can change to that one. Please let me know if you find something weird.

Your custom database seems to be ok given that otherwise it would have given you problems with that version, so there should be something related with the kraken2 server.

I would like to know what is failing, because this problem will appear if someone runs the workflow in real time. Is it possible to know if you are using any extra parameter? How many sequences do you have and if there is a classification for them? I would like to reproduce the problem.

**Comment by nggvs** [comment] 2023-11-22 13:52
Hi @nataliering ,
new release (v2.7.0) is ready. It would be nice if you switch to this version as the pre-release is not stable. Also, if you consider the problem has already been solved, I would appreciate that you close the issue.

**Closed** 2023-12-12 11:02 UTC
Labels: question
